### ISSUE TITLE
Where are the full-text specifications?

### ISSUE THREAD

**Issue by hwellmann** [jakartaee/specifications#119]
Now that Jakarta EE 8 has been released, I was hoping to find all specification documents in this repository, but for most subprojects, there only seems to be Javadoc and an envelope document.

What about the full text, for example, the equivalent of https://download.oracle.com/otn-pub/jcp/persistence-2_2-mrel-spec/JavaPersistence.pdf for Jakarta Persistence?

**Comment by arjantijms** [comment]
Hi,

The spec documents have not been transferred yet, but this should happen
before long. Indeed, current Jakarta EE 8 relies on JavaDoc.. The envelope
is called the boilerplate spec.

Kind regards,
Arjan

**Comment by lutzhorn** [comment]
This question is also discussed on the [jakarta.ee-community mailinglist](https://www.eclipse.org/lists/jakarta.ee-community/msg01237.html).

**Comment by keilw** [comment]
Please keep in mind, that many of the old specifications were often written with proprietary tools like MS Word etc. and transferring all of them to a new open form is both technically and legally a challenge.

With Jakarta NoSQL entering the platform as a candidate for future versions, there are also possible touchpoints with the mentioned Jakarta Persistence spec (@arjantijms knows we had those in the JNoSQL mailing list) so some specs that qualify for this kind of modularization may see the same CDI 2 already faced prior to Jakarta EE. Which obviously has further implications for the documents because a large monolithic one must be broken further apart.

Kind Regards,
Werner

**Comment by msohn** [comment]
Any ETA when this transfer of the full spec texts will conclude ?

Looking for the full text servlet 4.0 spec which I found here for JavaEE 8 https://download.oracle.com/otndocs/jcp/servlet-4-final-spec/index.html

**Comment by arjantijms** [comment]
@msohn We're currently in progress of doing this. A large amount of documents have been contributed and have their copyright assigned, but not all. The EF is actively seeking to clear the remainder.

As the documents have been converted to AsciiDoc from several other formats, this didn't always went perfectly, and manual updated are needed. In addition the terminology and references etc have to be updated. 

It's hard to give an exact ETA but it's definitely in progress now.

**Comment by kwsutter** [comment]
The effort of transferring the Specification source to the respective github repos is being tracked via this Project board:  https://github.com/eclipse-ee4j/jakartaee-platform/projects/2

Just to clean up the backlog, could we close out this Issue since this is being tracked elsewhere?  Thanks.

**Comment by kwsutter** [comment]
I'm going with lazy consensus to close out this Issue based on my comment from 27 days ago...  Thanks!

**Comment by DidierLoiseau** [comment]
> The effort of transferring the Specification source to the respective github repos is being tracked via this Project board: https://github.com/eclipse-ee4j/jakartaee-platform/projects/2

This link is broken, was it transferred somewhere else?
